### ISSUE TITLE
Wonderful talk! Good resources for learning modern C++?

### ISSUE THREAD

**Issue by ghost** [adhokshajmishra/opensource_aug_meetup#1]
Hi Adhokshaj,

Your talk yesterday was absolutely wonderful. Thank you so much!

Do you have any resources (books, websites etc) that you could recommend to coders with some programming background who would like to learn modern C++?

मानस

**Comment by adhokshajmishra** [comment]
This is one by Scott Meyers: https://www.amazon.in/Effective-Modern-Specific-Ways-Improve-ebook/dp/B00PGCMGDQ?_encoding=UTF8&keywords=c%2B%2B14&portal-device-attributes=desktop&qid=1503295184&ref_=sr_1_2&sr=8-2

There are many other books on C++11 and C++14 which you can follow. Hope this helps.
